### ISSUE TITLE
link to axelarscan when deploying tokens

### ISSUE THREAD

**Issue by canhtrinh** [axelarnetwork/axelarjs#226]
When deploying a token, link to axelarscan through the Initiated/Confirmed status, instead of just the top right buttons

**Comment by npty** [comment]
![Screenshot 2567-04-25 at 5 14 56 PM](https://github.com/axelarnetwork/axelarjs/assets/78221556/af053d9f-1a74-437a-8846-458f0070429f)

Not sure if i understand this correctly, but we already had multiple links to axelarscan. Feel free to reopen the issue if i misunderstand this 🙇🏻
