### ISSUE TITLE
cannot transfer a canonical token

### ISSUE THREAD

**Issue by canhtrinh** [axelarnetwork/axelarjs#240]
From Metavault (Steve 0x):

I try to bridge via ITS but facing lot of issues with the interchain.axelar.dev dapp

It let me first approve 2-3 times

after i wanted to bridge to linea but the tx was for scroll? and i need to topup my self gas because the tx was without gas transfer.

now i am again trying to bridge to linea but this time i can press 100 times the cta for Transfer xxxx token to linea -> nothing happens

no errors in the console, network traffic each time when pressing the CTA -> rpc.walletconnect (even i am not connected via it)

tried to connect via metamask mobil & wallet connect -> nothing happend after scanning

https://interchain.axelar.dev/polygon/0x2760E46d9BB43dafCbEcaad1F64b93207f9f0eD7

**Comment by alanrsoares** [comment]
fixed and released
