### ISSUE TITLE
Metamask appears in 3 places when attempting to connect wallet on ITS portal

### ISSUE THREAD

**Issue by Olanetsoft** [axelarnetwork/axelarjs#246]
![telegram-cloud-photo-size-2-5391286578120349191-y](https://github.com/axelarnetwork/axelarjs/assets/45847909/35b47d2a-8efd-4234-839d-8bb2a4971f8b)

**Comment by npty** [comment]
Looks like this is already fixed.

<img width="748" alt="image" src="https://github.com/axelarnetwork/axelarjs/assets/78221556/49a2f374-79bd-4e82-a547-8360a2cb09fd">
