### ISSUE TITLE
ITS Portal cannot deploy tokens - It’s stuck on “Check Your Wallet"

### ISSUE THREAD

**Issue by Olanetsoft** [axelarnetwork/axelarjs#274]
On Mainnet:

![image](https://github.com/axelarnetwork/axelarjs/assets/45847909/6fe53b0a-843d-4676-83a8-587c249cd905)

**Comment by canhtrinh** [comment]
root cause is in underlying contracts. being addressed now

**Comment by canhtrinh** [comment]
this issue was fixed downstream. closing ticket
