### ISSUE TITLE
No wallet confirmation popup on ITS portal - mainnet

### ISSUE THREAD

**Issue by Olanetsoft** [axelarnetwork/axelarjs#287]
"We were trying to use https://interchain.axelar.dev/ to launch the Token on OP/Base/Blast. But the create flow doesn't seem to move past the confirmation stage. I tried twice, both leading to the flow not moving to the wallet to sign/pay/confirm. But I'm now seeing two tokens on https://interchain.axelar.dev/interchain-tokens."

https://github.com/axelarnetwork/axelarjs/assets/45847909/8091ea65-a56c-4b64-8433-8d67724dac9e

**Comment by Olanetsoft** [comment]
Sure. @canhtrinh Thought I added it, sorry.

token address
attempt 1: 0x828B061Ae155e8782D616f561008C2f8731A1a1d 
attempt 2: 0x39c1cAD6880aA7027dA2E31E0feC3522D7dE55f7

browser: 
firefox

**Comment by canhtrinh** [comment]
@Olanetsoft this looks to be the same root cause as this: https://github.com/axelarnetwork/axelarjs/issues/288. what wallet were they using, do you know?

**Comment by Olanetsoft** [comment]
Browser: firefox

Wallet: MetaMask @canhtrinh

**Comment by canhtrinh** [comment]
ok, still trying to determine a patch for this identified root cause. we're considering just removing all other wallet options from the UI for now to unblock folks. 
@Olanetsoft we have that fix in testnet, can you try seeing if they can get it to work there?

**Comment by canhtrinh** [comment]
@Olanetsoft confirmed that the fix deployed in this version (https://github.com/axelarnetwork/axelarjs/blob/env/mainnet/apps/maestro/CHANGELOG.md#036) addressed their issue, and that the partner tried deploying in testnet successfully. this was just promoted to mainnet, so closing this ticket
