### ISSUE TITLE
Register Button Keeps Loading Without Confirmation Popup After Chain Selection

### ISSUE THREAD

**Issue by Olanetsoft** [axelarnetwork/axelarjs#288]
It works fine on the testnet but fails on the mainnet.  Here is the token address on eth mainnet. 0xe97F6dDE78b11B58cB3e394F15ab592Cb2ACd290

**Comment by canhtrinh** [comment]
the root cause of this is a known UI issue, i'll try to patch a fix this week. can you tell me:
* what wallet the user used?
* what browser?

**Comment by Olanetsoft** [comment]
I am confirming this and will give you feedback soon.

**Comment by Olanetsoft** [comment]
Tried on Chrome and Firefox. The wallet is MetaMask

**Comment by canhtrinh** [comment]
still addressing the actual root cause of the issue, but there is a "fix" (more like a technical simplification) we have live in testnet now. can you ask if they can try going through the same steps on testnet and seeing that works for them?

**Comment by canhtrinh** [comment]
@Olanetsoft confirmed that the fix deployed in this version (https://github.com/axelarnetwork/axelarjs/blob/env/mainnet/apps/maestro/CHANGELOG.md#036) addressed their issue, and that the partner tried deploying in testnet successfully. this was just promoted to mainnet, so closing this ticket
