### ISSUE TITLE
Unable to register DOGE2M token on another chain on mainnet portal

### ISSUE THREAD

**Issue by Olanetsoft** [axelarnetwork/axelarjs#339]
**Describe the bug**
DOGE2M cannot register their token on additional chains (e.g., Base and BNB) on the mainnet.  0x104d695117b94fF82Db0bC1Fd55D788516742377

**To Reproduce**
1. Go to the token page: https://interchain.axelar.dev/ethereum/0x104d695117b94fF82Db0bC1Fd55D788516742377
2. Click on BNB and Base; there isn't an option to confirm on the wallet, as it's disabled

**Screenshots / Video**

https://github.com/axelarnetwork/axelarjs/assets/45847909/0f290f0c-819d-4e7b-a467-86450c66d410

![photo_2024-04-15 16 58 40](https://github.com/axelarnetwork/axelarjs/assets/45847909/fa11726c-684b-4945-b3ee-526ce6d594f3)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**Please feel free to addd any other context about the problem here.

**Comment by canhtrinh** [comment]
deleted the phantom record, ask the partner to try again @Olanetsoft ?

**Comment by Olanetsoft** [comment]
> deleted the phantom record, ask the partner to try again @Olanetsoft ?

I have reached out to the dev, awaiting his feedback.

**Comment by Olanetsoft** [comment]
Confirmed working!
