### ISSUE TITLE
No confirmation pop up to deploy token remotely

### ISSUE THREAD

**Issue by Olanetsoft** [axelarnetwork/axelarjs#366]
**Describe the bug**
This token, 0xEAc9873291dDAcA754EA5642114151f3035c67A2, is deployed on BNB on the mainnet. An attempt to deploy on Base failed as there was no confirmation pop-up. Even after clearing the cache, it doesn't work.

**To Reproduce**
1. Go to https://interchain.axelar.dev/binance/0xEAc9873291dDAcA754EA5642114151f3035c67A2
2. Click on Base
3. Click on register token

**Screenshots**

https://github.com/axelarnetwork/axelarjs/assets/45847909/5bdd43c7-a54a-4f8d-a0ed-27be85fd54b5

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version

**Comment by npty** [comment]
I've debugged quickly from the network tab and found the execution reverted log was printed continuously.

![image](https://github.com/axelarnetwork/axelarjs/assets/78221556/710ff5fa-5c06-4a30-96f7-9a2bf347a8eb)
