### ISSUE TITLE
Token registration on Ethereum not being picked up by portal

### ISSUE THREAD

**Issue by benjamin852** [axelarnetwork/axelarjs#459]
**Describe the bug**
A user is able to successfully [register his token](https://interchain.axelar.dev/binance/0xfFC9388A855bda855258c441940E1b3577353E5F) on several blockchains on the portal. On ethereum he is able to press the register button and trigger a tx which [executes](https://axelarscan.io/gmp/0x05e0588524c9801f6dfc29210ecb431451d1b484673c2dbdd330f6f8a429d502) successfully. I confirmed on etherscan that the token is registered with ITS by querying the `validTokenManager()` function with the `interchainTokenId` that was logged in the tx the user shared. 

The issue is that the portal never marks the ethereum registration as complete. It shows ethereum as an unregistered blockchain for that token. When I check the [api](https://axelarscan.io/gmp/0x05e0588524c9801f6dfc29210ecb431451d1b484673c2dbdd330f6f8a429d502) as well ethereum has `isRegistered: false`

**To Reproduce**
1. Register the token on the portal 
2. Register on ethereum
3. Wait for the tx to go through
4. Token will remain unregistered on ethereum

**Expected behavior**

**Screenshots**
Token unregistered on portal
<img width="400" alt="Screenshot 2024-09-30 at 11 16 45 AM" src="https://github.com/user-attachments/assets/2ed35200-db9b-4d7e-a659-f55f9d49c028">

Token registration successful on chain
<img width="1093" alt="Screenshot 2024-09-30 at 11 17 08 AM" src="https://github.com/user-attachments/assets/0a84d8f9-927d-491f-9fea-98900f6a4125">

Token registered on ethereum on ITS
<img width="539" alt="Screenshot 2024-09-30 at 11 17 56 AM" src="https://github.com/user-attachments/assets/7810c41d-c203-420f-bac0-a6a7a085ad28">
Token address (referencing tx hash for registration)
<img width="836" alt="Screenshot 2024-09-30 at 11 19 54 AM" src="https://github.com/user-attachments/assets/793d6e82-9d39-4098-98e3-ed82e50a151d">
Tx hash for registration matching timestamp of registration
<img width="937" alt="Screenshot 2024-09-30 at 11 18 01 AM" src="https://github.com/user-attachments/assets/8a6551c6-ad93-403a-a205-325460d53416">

**Comment by canhtrinh** [comment]
thanks @benjamin852 . this is an edge case of a remote token being deployed successfully but not captured in an offline database. to unblock the user, i've recovered the transaction, so the ethereum card should appear now on the UI. we'll otherwise look to root cause this edge case further
